### ISSUE TITLE
Two different enum types cannot share a value

### ISSUE THREAD

**Issue by cdalzell651** [shopgun/graphql-erlang-tutorial#48]
When writing a query with two enum input types, if they share a value, and it is used, it results in an error: 
```
query simple_group {
  groupBy(fields: {proxy: [port] attacker: [port]}){
    id
  }
}
```
Returns:
```
{
  "errors": [
    {
      "type": "error",
      "message": "{error,
    #{key =>
          {param_mismatch,
              {enum,<<\"proxy\">>,
                  {enum_type,<<\"attacker_victim\">>,
                      <<\"No description provided\">>,juno_enum,#{},
                      #{0 =>
                            {enum_value,<<\"userName\">>,
                                <<\"No descriptions supported yet\">>,#{},
                                undefined},
                        1 =>
                            {enum_value,<<\"hostName\">>,\
                               <<\"No descriptions supported yet\">>,#{},
                                undefined},
                        2 =>
                           {enum_value,<<\"ip\">>,
                                <<\"No descriptions supported yet\">>,#{},
                                undefined},
                        3 =>
                            {enum_value,<<\"mac\">>,
                                <<\"No descriptions supported yet\">>,#{},
                                undefined},
                        4 =>
                            {enum_value,<<\"role\">>,
                                <<\"No descriptions supported yet\">>,#{},
                                undefined},
                        5 =>
                            {enum_value,<<\"protocol\">>,
                                <<\"No descriptions supported yet\">>,#{},
                                undefined},
                        6 =>
                            {enum_value,<<\"port\">>,
                               <<\"No descriptions supported yet\">>,#{},
                                undefined},
                        7 =>
                            {enum_value,<<\"packetsSent\">>,
                                <<\"No descriptions supported yet\">>,#{},
                                undefined},
                        8 =>
                            {enum_value,<<\"bytesSent\">>,
                                <<\"No descriptions supported yet\">>,#{},
                                undefined}}}}},
      message =>
          <<\"The enum value is of type attacker_victim but used in a context where an enum value of type proxy was expected\">>,
      path => [<<\"document\">>,<<\"simple_group\">>,<<\"groupBy\">>,<<\"proxy\">>]}}"
    }
  ]
}
```
Crucially, `"The enum value is of type attacker_victim but used in a context where an enum value of type proxy was expected"`, even though both contain the value `proxy`.

**Comment by jlouis** [comment]
Yes, this is a "somewhat known limitation" currently in the system. The problem is that we are doing a lookup on the enum value in order to determine its type to see if it is a valid type. Currently, the type checker has no multiplicity on that, so it picks one of the types only. This of course leads to errors down the chain.

The right solution is to map an enum value to a list of *possible* types. And then verify if there is a match between the possible types and the expected one, coercing the type to the right value in the process.

However, I cannot remember what the specification says about this. I think it allows it, but I'm not sure. In any case, the error report could be better here.

It is just one of the many things "i did not get around to solving yet." If you are interested in trying to fix it, I'll happily give some pointers to what I think should be done. I'll probably get around to fixing this myself at some point later, but there is currently no timeframe on that.

**Comment by cdalzell651** [comment]
Thanks for the quick response, I'll try and work around that then.

**Comment by jlouis** [comment]
Feel free to create an issue on the `graphql-erlang` repository. Especially so if the spec says that it is allowed. In principle it shouldn't be too hard to support.
